[package]
name = "testing"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest


[dependencies]
starknet = ">=2.3.0-rc0"

# foo = { path = "vendor/foo" }

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
casm = true
